name: Build and push digital-land-python to public ECR
on:
  push:
    branches:
      # - main # TODO reinstate this before merge
      - run-pipeline-commands-locally

jobs:
  build:

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
        python-version: 3.8
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1
    - name: Build & Push
      run: |
        make docker-build
        make docker-push

