# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Test Workflow
on:
  push:
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7, 3.8]

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Make Init
      run: |
        make init
    - name: Test ogr2ogr
      run: |
        ogr2ogr --version
    - name: Test ogr2ogr
      run: |
        ogr2ogr -oo DOWNLOAD_SCHEMA=NO -lco GEOMETRY=AS_WKT -lco LINEFORMAT=CRLF -f CSV -nlt MULTIPOLYGON -nln MERGED --config OGR_WKT_PRECISION 10 temp tests/data/resource_examples/kml.resource    
    - name: Print output
      run: |
        cat temp/MERGED.csv
